cloud:
  aws:
    s3:
      bucket: talken-bucket
    credentials:
      access-key: AKIAR7IEDENGRTJNFFLD
      secret-key: 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
    region:
      static: ap-northeast-2
    stack:
      auto: false
    cloud_front:
      file_url_format: https://dkf139jhtl3zc.cloudfront.net/

spring:
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/talken
    username: root
    password: root
#    url: jdbc:mariadb://mariadb.cfq7fgtifzjh.ap-northeast-2.rds.amazonaws.com:3306/talken
#    username: admin
#    password: test1234
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
      connection:

#      globally_quoted_identifiers: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDB103Dialect
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  secret-key: c2VydmVyLWJhY2tlbmQtc2VydmVyLWFzZGZhc2RnZXdya2plbGdhaW9kdS15b295ZW9uLXRhbGtlbi1iYWNrZW5kCg==
  expiration: 120000
  redis:
    host: localhost
    port: 6379

oauth:
  kakao:
    client-id: c004cdf773860f139301c52f6144b697
    url:
      auth: https://kauth.kakao.com
      api: https://kapi.kakao.com
  naver:
    secret: nL6ZaxF5wX
    client-id: ELvRWBtrLDyzqA6zlW8f
    url:
      auth: https://nid.naver.com
      api: https://openapi.naver.com

management:
  endpoint:
    health:
      show-details: always
  endpoints:

    web:
      exposure:
        include: "*"
        exclude: "env, beans"

logging:
  pattern:
    file: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"
  file:
    name: talken.log
    path: /server/logs
  level:
    org:
      com.example.talkenbackend: DEBUG
server:
  tomcat:
    mbeanregistry:
      enabled: true